services:
  - type: web
    name: meu-projeto-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    rootDir: backend
  - type: web
    name: meu-projeto-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
